version: '3'
services:
  foodboxdb:
    container_name: foodboxdb
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=rootpasswd
    - MYSQL_DATABASE=foodboxdb
    - MYSQL_USER=user
    - MYSQL_PASSWORD=userpasswd
    restart: always
    ports:
    - 3306:3306
    volumes:
    - foodboxdb:/var/lib/mysql
    network_mode: host
    
  foodbox-service-rest:
    container_name: foodbox-service-rest
    image: foodbox-service-rest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - foodboxdb
    ports:
    - 8081:8081
    restart: always
    network_mode: host
    
volumes:
  foodboxdb: