version: '3'
services:
  foodboxdb:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
    - MYSQL_DATABASE=database
    restart: always
    ports:
    - 3306:3306
    networks:
      - backend
    
  foodbox-service-rest:
    image: foodbox-service-rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - foodboxdb
    ports:
    - 8081:8081
    restart: always
    networks:
      - backend

networks: 
  backend: 
    
