version: '3'
services:
  foodboxdb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
    restart: always
    ports:
    - 3306:3306
    network_mode: host
    
  foodbox-service-rest:
    image: foodbox-service-rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - foodboxdb
    environment:
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user123
      - DATABASE_URL=jdbc:mysql://foodboxdb:3306/foodboxdb?createDatabaseIfNotExist=true&useSSL=false&enabledTLSProtocols=TLSv1.2
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    ports:
    - 8081:8081
    restart: always
    network_mode: host
    
