version: '3'
services:
  foodboxdb:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
    - MYSQL_DATABASE=database
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    restart: always
    ports:
    - 3306:3306
    networks:
      - backend
    
  foodbox-service-rest:
    image: foodbox-service-rest:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
    SPRING_DATASOURCE_URL:jdbc:mysql://foodboxdb:3306/database?autoReconnect=true&useSSL=false&enabledTLSProtocols=TLSv1.2
    depends_on:
    - foodboxdb
    ports:
    - 8081:8081
    restart: always
    networks:
      - backend

networks: 
  backend: 
    
