version: '3'
services:
  foodboxdb:
    container_name: foodboxdb
    image: mysql:8.0.26

    restart: always
    ports:
    - 3306:3306
    volumes:
    - foodboxdb:~/var/lib/mysql
    
  foodbox-service-rest:
    container_name: foodbox-service-rest
    image: foodbox-service-rest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - foodboxdb
    ports:
    - 8081:8081
    restart: always
    
volumes:
  foodboxdb: