version: '3.8'
services:
  db: 
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=foodboxdb
    - MYSQL_USER=root
    - MYSQL_PASSWORD=pw
    restart: always
    ports: 
    - 3306:3306
    volumes:
    - foodboxdb:/var/lib/mysql
    
  foodbox-service-rest:
    container_name: foodbox-service-rest
    restart: on-failure
    image: foodbox-service-rest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - db
    ports:
    - 8081:8081
    environment:  
      - DATABASE_HOST=db  
      - DATABASE_USER=root
      - DATABASE_PASSWORD=pw
      - DATABASE_NAME=foodboxdb  
      - DATABASE_PORT=3306
    
volumes:
  foodboxdb: